baseurl = "http://www.schnuddelhuddel.de"
languageCode = "en-gb"

enableEmoji = true
enableGitMode = true
enableRobotsTXT = true
title = "Pragmatic"
# theme = "hpstr"
theme = "hugo-icarus-theme"
pluralizelisttitles = false
PygmentsCodeFences = true
pygmentsStyle = "monokai"
paginate = 10
footnotereturnlinkcontents = "↩"

disqusShortname = "pragmatic-1"

# disable_widgets = true

# define which types of pages should be shown. By default the type with the most regular pages
mainSections = ["post","posts"]

[blackfriday]
   extensions = ["hardLineBreak"]
   plainIDAnchors = true
   hrefTargetBlank = true


[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
    # Tell me who you are
    author = "Mario Martelli"
    bio = "Pragmatic Integrator"
    location = "Europe"
    site_description = ""
    copyright  = "Mario Martelli --  [Imprint](/imprint) "  
    extFooter  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    avatar = "logo/Avatar.png"
    logo = "logo/logo.png"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Start"
    link   = "/"

[[params.menu]]
    before = true
    label  = "About"
    link   = "about/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

[[params.menu]]
    before = false
    label  = "Cycling"
    link   = "https://www.martelli.de"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/schnuddelhuddel" # github.com/digitalcraftsman"

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "mgmart"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = "" # "3718126"
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "schnuddelhuddel"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true

# [params]
#    subtitle = "Integration of everything"
#    background = "/images/witewall_3.png"
#    [params.author]
#       name = "Mario"
#       avatar = "/images/Avatar.png"
#       bio = "Pragmatic Integrator"
#       github = "mgmart"
#    [params.image]
#       feature = "/images/abstract-4.jpg"
#       credit = "dargadgetz"
#       creditlink = "http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/"
      